### ISSUE TITLE
java.lang.NoClassDefFoundError: org/glassfish/jersey/internal/inject/AbstractBinder

### ISSUE THREAD

**Issue by yushkevich** [Labs64/NetLicensing-Gateway#20]
Runtime exception during controller call.
```15-Oct-2019 09:43:12.173 SEVERE [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log StandardWrapper.Throwable
	java.lang.NoClassDefFoundError: org/glassfish/jersey/internal/inject/AbstractBinder
		at java.lang.ClassLoader.defineClass1(Native Method)
		at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
		at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2395)
		at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:857)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1329)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1182)
		at org.glassfish.jersey.jaxb.internal.JaxbAutoDiscoverable.configure(JaxbAutoDiscoverable.java:58)
		at org.glassfish.jersey.model.internal.CommonConfig.configureAutoDiscoverableProviders(CommonConfig.java:624)
		at org.glassfish.jersey.server.ResourceConfig.configureAutoDiscoverableProviders(ResourceConfig.java:811)
		at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:447)
		at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184)
		at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350)
		at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
		at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255)
		at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347)
		at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392)
		at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177)
		at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369)
		at javax.servlet.GenericServlet.init(GenericServlet.java:158)
		at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1144)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1091)
		at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:985)
		at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4885)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5199)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)
	Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.inject.AbstractBinder
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1360)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1182)
		... 38 more
```

**Comment by yushkevich** [comment]
result
![2019-10-15_10-30-44](https://user-images.githubusercontent.com/3961540/66809883-e291f700-ef36-11e9-9613-4334d8a71fc5.png)
